# Generated by Django 2.2.17 on 2021-01-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('chat', '0002_auto_20210115_1918'), ('chat', '0003_auto_20210115_1936'), ('chat', '0004_auto_20210115_1939'), ('chat', '0005_auto_20210115_2022')]

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='thread',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='chat.Message', verbose_name='Messages'),
        ),
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='thread', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.RemoveField(
            model_name='thread',
            name='messages',
        ),
        migrations.AddField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='threads', to='chat.Message', verbose_name='Messages'),
        ),
    ]
