# Generated by Django 2.2.17 on 2021-01-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-id'], 'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
    ]
