# Generated by Django 2.2.17 on 2021-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ManyToManyField(related_name='_contact_contact_+', to='chat.Contact', verbose_name='Contact'),
        ),
    ]
