# Generated by Django 2.2.17 on 2021-01-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_contact_contacts_+', to='chat.Contact', verbose_name='Contacts'),
        ),
    ]
