/* Example constants
export const GET_BALANCE = "GET_BALANCE"
export const GET_BALANCE_SUCCEEDED = "GET_BALANCE_SUCCEEDED"
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED"
*/

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_SCHOOLS_SUCCEEDED = 'GET_SCHOOLS_SUCCEEDED';
export const GET_SCHOOLS_FAILED = 'GET_SCHOOLS_FAILED';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCEEDED = 'GET_PROFILE_SUCCEEDED';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCEEDED = 'UPDATE_PASSWORD_SUCCEEDED';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_SUCCEEDED = 'UPDATE_EMAIL_SUCCEEDED';
export const UPDATE_EMAIL_FAILED = 'UPDATE_EMAIL_FAILED';

export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_PHONE_SUCCEEDED = 'UPDATE_PHONE_SUCCEEDED';
export const UPDATE_PHONE_FAILED = 'UPDATE_PHONE_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCEEDED = 'UPDATE_PROFILE_SUCCEEDED';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const UPDATE_PROFILE_PHOTO = 'UPDATE_PROFILE_PHOTO';
export const UPDATE_PROFILE_PHOTO_SUCCEEDED = 'UPDATE_PROFILE_PHOTO_SUCCEEDED';
export const UPDATE_PROFILE_PHOTO_FAILED = 'UPDATE_PROFILE_PHOTO_FAILED';
