# Generated by Django 2.2.17 on 2021-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
