export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_THREADS = 'GET_THREADS';
export const GET_THREADS_SUCCEEDED = 'GET_THREADS_SUCCEEDED';
export const GET_THREADS_FAILED = 'GET_THREADS_FAILED';

export const CREATE_THREADS = 'CREATE_THREADS';
export const CREATE_THREADS_SUCCEEDED = 'CREATE_THREADS_SUCCEEDED';
export const CREATE_THREADS_FAILED = 'CREATE_THREADS_FAILED';
