# Generated by Django 2.2.17 on 2021-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, unique=True, verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Week Day',
                'verbose_name_plural': 'Week Days',
            },
        ),
        migrations.DeleteModel(
            name='CustomText',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
