# Generated by Django 2.2.17 on 2021-01-13 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'kindergarten'), (2, 'first'), (3, 'second'), (4, 'third'), (5, 'forth'), (6, 'fifth'), (7, 'sixth'), (8, 'seventh'), (9, 'eigth'), (10, 'freshman'), (11, 'softmore'), (12, 'junior'), (13, 'senior')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'parent'), (4, 'school')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'StudentType',
                'verbose_name_plural': 'UserTypes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone number')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='School')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Student ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Profile pic')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.Grade', verbose_name='Grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.UserType', verbose_name='User Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
