# Generated by Django 2.2.17 on 2021-01-12 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_parent_profile_school_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'kindergarten'), (2, 'first'), (3, 'second'), (4, 'third'), (5, 'forth'), (6, 'fifth'), (7, 'sixth'), (8, 'seventh'), (9, 'eigth'), (10, 'freshman'), (11, 'softmore'), (12, 'junior'), (13, 'senior')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'parent'), (4, 'school')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'StudentType',
                'verbose_name_plural': 'UserTypes',
            },
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.UserType', verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.Grade', verbose_name='Grade'),
        ),
    ]
