# Generated by Django 2.2.17 on 2021-01-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("school", "School"),
                ],
                default="student",
                max_length=50,
                verbose_name="User Type",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
